alter table PLAYGROUND_SAMPLE_ENTITY add constraint FK_PLAYGROUND_SAMPLE_ENTITY_ON_PARENT foreign key (PARENT_ID) references PLAYGROUND_SAMPLE_ENTITY(ID);
create index IDX_PLAYGROUND_SAMPLE_ENTITY_ON_PARENT on PLAYGROUND_SAMPLE_ENTITY (PARENT_ID);
