alter table PLAYGROUND_SAMPLE_ENTITY add constraint FK_PLAYGROUND_SAMPLE_ENTITY_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_PLAYGROUND_SAMPLE_ENTITY_USER on PLAYGROUND_SAMPLE_ENTITY (USER_ID);
