-- begin PLAYGROUND_SAMPLE_ENTITY
alter table PLAYGROUND_SAMPLE_ENTITY add constraint FK_PLAYGROUND_SAMPLE_ENTITY_ON_PARENT foreign key (PARENT_ID) references PLAYGROUND_SAMPLE_ENTITY(ID)^
alter table PLAYGROUND_SAMPLE_ENTITY add constraint FK_PLAYGROUND_SAMPLE_ENTITY_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PLAYGROUND_SAMPLE_ENTITY_ON_PARENT on PLAYGROUND_SAMPLE_ENTITY (PARENT_ID)^
create index IDX_PLAYGROUND_SAMPLE_ENTITY_ON_USER on PLAYGROUND_SAMPLE_ENTITY (USER_ID)^
-- end PLAYGROUND_SAMPLE_ENTITY
